[deps]
DiffEqFinancial = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
PathSignatures = "4efb4129-5e83-47d2-926d-947c0e6cb76d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
