name = "PathSignatures"
uuid = "4efb4129-5e83-47d2-926d-947c0e6cb76d"
authors = ["aleCombi <alecombi94@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
